name: homefe
description: A special Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'
  flutter: '>=3.38.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: 5.9.2
  flutter_bloc: 9.1.1
  rss_dart: 1.0.14
  html: 0.15.6
  intl: 0.20.2
  go_router: 17.1.0
  url_launcher: 6.3.2
  timeago: 3.7.1
  cached_network_image: 3.4.1
  json_annotation: 4.9.0
  collection: 1.19.1
  logger: 2.7.0
  flutter_svg: 2.2.4
  shared_preferences: 2.5.4
  # flutter_secure_storage: 9.2.4 # AFTER HTTPS, WASM, remove shared_preferences
  share_plus: 12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  json_serializable: 6.8.0
  build_runner: 2.4.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app-logo.svg
    - assets/app-logo-light.svg
    - assets/thumbnails/random.svg
    - assets/thumbnails/phoronix.svg
    - assets/thumbnails/slashdot.svg
    - assets/thumbnails/techcrunch.svg
    - assets/thumbnails/dpreview.svg
    - assets/thumbnails/toms-hardware.svg
    - assets/thumbnails/ars-technica.svg
    - assets/thumbnails/hacker-news.svg
    - assets/thumbnails/the-register.svg
    - assets/thumbnails/the-verge.svg
    - assets/thumbnails/wired.svg
    - assets/flags/flag-en.svg
    - assets/flags/flag-th.svg
    - assets/flags/flag-fi.svg
    - assets/flags/flag-de.svg
    - assets/flags/flag-jp.svg
