FROM ghcr.io/cirruslabs/flutter:3.38.6
    
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends htop clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

